### ISSUE TITLE
Add KebechetAdministrator functionality [?pt]

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/workflow-helpers#148]
- [x] Add new KebechetRunUrlMessage to thoth-messaging.
- [x] Add new subcommand to Workflow helper
- [x] Add new file to implement KebechetAdministrator to schedule kebechet workflows. 
      -  It would receive parameters - PackageName, PackageVersion, PackageIndex, Solver: str, MessageType.Name (str)
      -  Check what messages it can handle - {HashMismatch, MissingPackage, MissingVersion, CVEProvidedMessage, SolvedMessage}
      -  Based on if SolvedMessage (query using name and index only) and schedule only for repo's that don't have the version number == PackageVersion.
      -  For all other current message types, query using version, name, and index, and schedule for everything. 
- [x]  Send KebechetRunUrlMessage for all the repos kebechet needs to be scheduled for. {Repo name, Installation-ID, Private}
- [x]  {Investigator task to consume and react on KebechetRunUrlMessage.} 
- [x]  Add a new workflow for KebechetAdministrator in thoth-application template
- [x]  Add method in common to schedule this KebechetAdministrator
- [x] Investigator needs to call KebechetAdministrator in common's method for {HashMismatch, MissingPackage, MissingVersion, SolvedMessage, CVEProvidedMessage} For example - [link](https://github.com/thoth-station/investigator/blob/d0cd2a27c3d3830e2fa9cbbb7b3a214050a0d701/investigator/investigator/missing_version/investigate_missing_version.py#L64)

Ref - 
Method in graph to call - `get_kebechet_github_installations_info_for_python_package_version` https://github.com/thoth-station/storages/pull/2046

**Comment by pacospace** [comment]
> * [ ]  Add new subcommand to Workflow helper
> * [ ]  Add new file to implement KebechetAdministrator to schedule kebechet workflows.
>   -  It would receive parameters - PackageName, PackageVersion, PackageIndex, Solver: str, MessageType.Name (str)
>   -  Check what messages it can handle - {HashMismatch, MissingPackage, MissingVersion, SolvedMessage}
>   -  Based on if SolvedMessage (query using name and index only) and schedule only for repo's that don't have the version number == PackageVersion.
>   -  For all other current message types, query using version, name, and index, and schedule for everything.
> * [ ]   Send KebechetRunUrlMessage for all the repos kebechet needs to be scheduled for. {Repo name, Installation-ID, Private}
> * [ ]   {Investigator task to consume and react on KebechetRunUrlMessage.}
> * [ ]   Add a new workflow for KebechetAdministrator in thoth-application template
> * [ ]   Add method in common to schedule this KebechetAdministrator
> * [ ]  Investigator needs to call KebechetAdministrator in common's method for {HashMismatch, MissingPackage, MissingVersion, SolvedMessage} For example - [link](https://github.com/thoth-station/investigator/blob/d0cd2a27c3d3830e2fa9cbbb7b3a214050a0d701/investigator/investigator/missing_version/investigate_missing_version.py#L64)
> 
> Ref -
> Method in graph to call - `get_kebechet_github_installations_info_for_python_package_version` [thoth-station/storages#2046](https://github.com/thoth-station/storages/pull/2046)

      -  Based on if SolvedMessage (query using name) and schedule only for repo's that don't have the version number == PackageVersion.

I generalized query to have only package_name because for user software stack index URL is not always present.

```
    def get_kebechet_github_installations_info_for_python_package_version(
        self,
        package_name: str,
        *,
        package_version: Optional[str] = None,
        index_url: Optional[str] = None,
        os_name: Optional[str] = None,
        os_version: Optional[str] = None,
        python_version: Optional[str] = None,
    ) -> dict:
        """Return info about repo containing Python Package in the software stack.

        Examples:
        >>> from thoth.storages import GraphDatabase
        >>> graph = GraphDatabase()
        >>> graph.get_kebechet_github_installations_info_for_python_package_version(
            package_name='click'
        )
        {
            'thoth-station/jupyter-nbrequirements': 
                {
                    'installation_id': '193650988',
                    'private': False,
                    'package_name': 'pyzmq',
                    'package_version': '7.1.2',
                    'index': None}
                }
        }

        Examples:
        >>> from thoth.storages import GraphDatabase
        >>> graph = GraphDatabase()
        >>> graph.get_kebechet_github_installations_info_for_python_package_version(
            package_name='click'
            index_url="https://pypi.org/simple",
        )

        {
            'thoth-station/jupyter-nbrequirements': 
                {
                    'installation_id': '193650988',
                    'private': False,
                    'package_name': 'click',
                    'package_version': '7.1.2',
                    'index': 'https://pypi.org/simple'}
                }
        """
```

**Comment by saisankargochhayat** [comment]
> I generalized query to have only package_name because for user software stack index URL is not always present unless the user accepted advised stack, in that case when we sync the user software stack we would find the index.
> 
> This is required because we filter by index and therefore a package name with index is not identified in the user software stack, although package and version might be there. WDYT? @saisankargochhayat @fridex

So for SolvedMessage query using `package_name`. So on the Administrator side, we check if the index is available for a user and it differs for a solved message we don't schedule another run. I think that makes sense.

**Comment by saisankargochhayat** [comment]
This can be closed as all related components are merged.
