### ISSUE TITLE
Handling missing artifacts 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/workflow-helpers#169]
3. removed artifact - e.g. build for py38 but sdist or other wheels are still present

All the three above can cause issues. So we should be able to detect removals of any of these. Any of these might cause the application would not assemble.

_Originally posted by @fridex in https://github.com/thoth-station/workflow-helpers/pull/154#discussion_r526287823_

How do we check this? I guess it should be a new message sent out by package update and investigator and kebechet admin can deal with that. WDYT?

There is also the case of changing hash and that is covered by HashMismatchMessage and Kebechet admin can already deal with that with this new logic.
_Originally posted by @pacospace  in https://github.com/thoth-station/workflow-helpers/pull/154#discussion_r527228888_

CC - @KPostOffice

**Comment by KPostOffice** [comment]
If an artifact goes missing it should cause a `HashMismatchMessage` to be sent because each hash corresponds to a different artifact.

**Comment by saisankargochhayat** [comment]
> If an artifact goes missing it should cause a `HashMismatchMessage` to be sent because each hash corresponds to a different artifact.

@pacospace in that case currently we run kebechet again, hoping thamos advise would create a new pipfile.lock with the available artefacts.

**Comment by pacospace** [comment]
> > If an artifact goes missing it should cause a `HashMismatchMessage` to be sent because each hash corresponds to a different artifact.
> 
> @pacospace in that case currently we run kebechet again, hoping thamos advise would create a new pipfile.lock with the available artefacts.

yes kebechet run again for all repo where that hash was present in their dependencies and adviser will relock the software stack, and we open PR saying the reason why (TBD)

**Comment by goern** [comment]
@pacospace @KPostOffice is this done?! or do we need to implement something?

**Comment by pacospace** [comment]
> @pacospace @KPostOffice is this done?! or do we need to implement something?

if HashMismatchMessage covers all cases described above, we should be good, and internal trigger should do the rest https://github.com/thoth-station/investigator/blob/master/thoth/investigator/hash_mismatch/investigate_hash_mismatch.py

**Comment by pacospace** [comment]
cc @KPostOffice

**Comment by KPostOffice** [comment]
/remove-lifecycle rotten

In progress

**Comment by pacospace** [comment]
@KPostOffice is this already implemented?
