### ISSUE TITLE
Missing package does not error

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/workflow-helpers#21]
```
Duration: 35 seconds
Parameters:
ceph_bucket_prefix: data
ceph_bucket_name: thoth
ceph_host: s3.upshift.redhat.com
deployment_name: ocp-test
THOTH_SECURITY_INDICATORS_JOB_ID: security-indicator-0da8c495
THOTH_DOCUMENT_ID: security-indicator-0da8c495
THOTH_SECURITY_INDICATORS_PACKAGE_NAME: black
THOTH_SECURITY_INDICATORS_PACKAGE_VERSION: *
THOTH_SECURITY_INDICATORS_PACKAGE_INDEX: https://tensorflow.pypi.thoth-station.ninja/index/rhel7.7/AVX2/simple
THOTH_SECURITY_INDICATORS_AGGREGATION_FUNCTION: process_data
THOTH_FORCE_SYNC: 0

STEP TEMPLATE PODNAME DURATION MESSAGE
✖ security-indicator-0da8c495 security-indicators
├-✔ download-package download-package/download-package security-indicator-0da8c495-3702534709 18s
├-✖ bandit bandit/bandit-from-dir security-indicator-0da8c495-1642427050 9s failed with exit code 1
└-⚠ cloc cloc/cloc-from-dir security-indicator-0da8c495-2968692625 0s pods "security-indicator-0da8c495-2968692625" is forbidden: exceeded quota: thoth-test-core-quota, requested: limits.cpu=700m, used: limits.cpu=15950m, limited: limits.cpu=16

✔ security-indicator-0da8c495.onExit exit-handler
└---✔ delete-pvc delete-pvc security-indicator-0da8c495-2337248660 4s
```

There is no packages matching `black` on `https://tensorflow.pypi.thoth-station.ninja/index/rhel7.7AVX2/simple`.  `download-package` should fail and `bandit` and `cloc` should never be scheduled.

**Comment by KPostOffice** [comment]
This might be an issue with the scripts exit code.

**Comment by KPostOffice** [comment]
pip doesn't allow `<package>===*`, if you're looking to get the most recent you should just use `pip install <package>` this still doesn't explain why the step succeeded but I thought it was worth noting

**Comment by KPostOffice** [comment]
When `workflow_helpers` was updated to use the more robust `app.sh` there was a space missing causing it to never run the python script and exit with 0.  Adding the fix now

**Comment by fridex** [comment]
> When `workflow_helpers` was updated to use the more robust `app.sh` there was a space missing causing it to never run the python script and exit with 0. Adding the fix now

Nice catch! :+1:
