### ISSUE TITLE
parse-solver fails to create message file 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/workflow-helpers#33]
**Describe the bug**
during a batch solver execution few [parse-solver](https://github.com/thoth-station/thoth-application/blob/master/solver/base/argo-workflows/parse-solver-inputs.yaml) workflow fails with ` level=error msg="executor error: open /mainctrfs/mnt/workdir/message: no such file or directory"`

**To Reproduce**
1. Go to middletier, and execute an init-job.
2. wait for the solver to finish
3. See error

**Additional context**
```
time="2020-07-31T06:03:23Z" level=info msg="Copying /mnt/workdir/message from from volume mount"
time="2020-07-31T06:03:23Z" level=info msg="Annotations monitor stopped"
time="2020-07-31T06:03:23Z" level=error msg="executor error: open /mainctrfs/mnt/workdir/message: no such file or directory"
time="2020-07-31T06:03:23Z" level=info msg="Killing sidecars"
time="2020-07-31T06:03:23Z" level=info msg="Alloc=5824 TotalAlloc=11844 Sys=70848 NumGC=4 Goroutines=9"
time="2020-07-31T06:03:23Z" level=fatal msg="open /mainctrfs/mnt/workdir/message: no such file or directory"
```

**Comment by pacospace** [comment]
I didn't see this error, it was solved in https://github.com/thoth-station/workflow-helpers/pull/36 and https://github.com/thoth-station/thoth-application/pull/243

**Comment by harshad16** [comment]
```
time="2020-08-18T10:02:02Z" level=error msg="executor error: open /mainctrfs/mnt/workdir/kafka_message: no such file or directory"
time="2020-08-18T10:02:02Z" level=info msg="Killing sidecars"
time="2020-08-18T10:02:02Z" level=info msg="Annotations monitor stopped"
time="2020-08-18T10:02:02Z" level=info msg="Alloc=5758 TotalAlloc=11880 Sys=71616 NumGC=4 Goroutines=9"
time="2020-08-18T10:02:02Z" level=fatal msg="open /mainctrfs/mnt/workdir/kafka_message: no such file or directory"
```
still persisting.

**Comment by pacospace** [comment]
I think new Argo version solved the problem. @harshad16 ? I run solver workflows successfully in test environment.

**Comment by harshad16** [comment]
Yes this has been fixed in stage deployment as well.
